# Generated by Django 5.1.3 on 2024-12-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0003_todoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('video_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
