# Generated by Django 5.1.3 on 2024-12-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0004_videotutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('query', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
